spring:
  application:
    name: vadebicicleta-equipamento-service
  datasource:
    auto: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
